name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-blocker
        path: web-blocker  

